version: '3.8'
services:
  app:
    # image: "${REGISTRY}cogini/foo-app"
    image: "${REPO_URL}:${IMAGE_TAG}"
    environment:
      - SECRET_KEY_BASE
      - DATABASE_URL
      - DATABASE_HOST=db
      - DATABASE_DB
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
    build:
      dockerfile: deploy/Dockerfile.alpine
      # dockerfile: deploy/Dockerfile.debian
      target: deploy
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
        REGISTRY: ${REGISTRY}
        MIX_ENV: prod
    # platform: "linux/arm64"
    # platform: "linux/amd64"
    ports:
      - "4000:4000"
    depends_on:
      - db

  dev:
    image: "foo-app-dev"
    environment:
      - MIX_ENV=dev
      - SECRET_KEY_BASE
      - DATABASE_URL
      - DATABASE_HOST=db
      - DATABASE_DB
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_DEFAULT_REGION
    # command: /bin/bash -c /srv/app/bin/app-start-dev
    # command: /srv/app/bin/app-start-dev
    # command: /bin/sh -c "/app/_build/prod/rel/app/bin/app foreground"

    # VSCode devcontainer needs something running
    # command: ["tail", "-f", "/dev/null"]
    # command: ["sleep", "infinity"]
    # command: /bin/sh -c "while sleep 1000; do :; done"
    command: mix phx.server
    build:
      dockerfile: deploy/Dockerfile.debian
      target: dev
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
        REGISTRY: ${REGISTRY}
        MIX_ENV: dev
    ports:
      - "4000:4000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    volumes:
      - ".:/app:delegated"
      # - 'nfsmount:/app'

  test:
    image: "app-test"
    environment:
      - MIX_ENV=test
      - DATABASE_URL
      - DATABASE_HOST=db
      - DATABASE_DB
    # command: sh -c 'while !</dev/tcp/db/5432; do sleep 1; done; set -ex mix test'
    # command: sh -c 'mix test'
    build:
      # dockerfile: deploy/Dockerfile.alpine
      dockerfile: deploy/Dockerfile.debian
      target: test
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
        REGISTRY: ${REGISTRY}
        MIX_ENV: test
    depends_on:
      - db

  vuln:
    image: "app-vuln"
    build:
      dockerfile: deploy/Dockerfile.alpine
      # dockerfile: deploy/Dockerfile.debian
      target: vuln
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
        REGISTRY: ${REGISTRY}

  # https://github.com/docker-library/docs/blob/master/postgres/README.md
  db:
    image: "app-db"
    # image: postgres:latest
    build:
      dockerfile: deploy/Dockerfile.postgres
      context: .
      args:
        REGISTRY: ${REGISTRY}
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"

  codebuild:
    # Custom build image for AWS CodeBuild
    image: "${REGISTRY}foo-app-ecs-build:latest"
    build:
      dockerfile: deploy/Dockerfile.codebuild
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
        REGISTRY: ${REGISTRY}

# volumes:
#   nfsmount:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#       device: ":${PWD}"
