version: "3.9"
services:
  # https://github.com/docker-library/docs/blob/master/postgres/README.md
  # https://geshan.com.np/blog/2021/12/docker-postgres/
  postgres:
    image: app-db:latest
    # image: postgres:14.1-alpine
    # image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    # hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres -d app_test"]
    #   start_period: 15s
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
  test:
    image: test:latest
    environment:
      - MIX_ENV=test
      - DATABASE_URL
      - DATABASE_HOST=postgres
      - DATABASE_DB
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    depends_on:
      - postgres
    volumes:
      - /junit-reports:/junit-reports
volumes:
  db:
    driver: local
