version: '3.8'
services:
  app:
    image: "${DOCKER_REPO}foo-app"
    environment:
      - SECRET_KEY_BASE
      - DATABASE_URL
    build:
      dockerfile: deploy/Dockerfile.alpine
      # dockerfile: deploy/Dockerfile.debian
      target: deploy
      context: .
      args:
        MIX_ENV: prod
        BUILDKIT_INLINE_CACHE: 1
      # cache_from:
      #   - "${DOCKER_REPO}foo-app-ecs-build-cache"
      #   # - "${DOCKER_REPO}foo-app"
    ports:
      - "4000:4000"
    depends_on:
      - db

  dev:
    image: "${DOCKER_REPO}foo-app-dev"
    environment:
      - SECRET_KEY_BASE
      - DATABASE_URL
    # command: /bin/bash -c /srv/click/bin/app-start-dev
    # command: /srv/click/bin/app-start-dev
    # command: /bin/sh -c "/app/_build/prod/rel/app/bin/app foreground"

    # VSCode devcontainer needs something running
    # command: ["tail", "-f", "/dev/null"]
    # command: ["sleep", "infinity"]
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      dockerfile: deploy/Dockerfile.debian
      target: dev
      context: .
      args:
        MIX_ENV: prod
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app:delegated
    # - 'nfsmount:/app'

  test:
    image: "${DOCKER_REPO}app-test"
    environment:
      - MIX_ENV=test
      - DATABASE_HOST=db
      - DATABASE_DB
    # command: sh -c 'while !</dev/tcp/db/5432; do sleep 1; done; set -ex mix test'
    # command: sh -c 'mix test'
    build:
      # dockerfile: deploy/Dockerfile.alpine
      dockerfile: deploy/Dockerfile.debian
      target: test
      context: .
      args:
        MIX_ENV: test
        BUILDKIT_INLINE_CACHE: 1
      # cache_from:
      #   - "type=local,src=${CACHE_DIR}"
      # cache_from:
      #   - "${DOCKER_REPO}foo-app-ecs-build-cache"
      # cache_from:
      #   - "type=local,src=${CACHE_DIR}"
      # cache_to:
      #   - "type=local,dest=${CACHE_DIR},mode=max"
    depends_on:
      - db

  # https://github.com/docker-library/docs/blob/master/postgres/README.md
  db:
    image: "${DOCKER_REPO}app-db"
    # image: postgres:latest
    build:
      dockerfile: deploy/Dockerfile.postgres
      context: .
      # args:
      #   MIX_ENV: prod
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"

# volumes:
#   nfsmount:
#     driver: local
#     driver_opts:
#       type: nfs
#       o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
#       device: ":${PWD}"
