version: '3.8'
services:
  app:
    image: app
    environment:
      - SECRET_KEY_BASE
      - DATABASE_URL
    build:
      dockerfile: deploy/Dockerfile.alpine
      target: deploy
      context: .
      args:
        MIX_ENV: prod
    ports:
      - 4000
    depends_on:
      - db

  test:
    image: app-test
    # command: sh -c 'while !</dev/tcp/db/5432; do sleep 1; done; set -ex mix test'
    command: sh -c 'mix test'
    environment:
      - DATABASE_HOST=db
    build:
      dockerfile: deploy/Dockerfile.alpine
      context: .
      target: test
      args:
        MIX_ENV: test
    depends_on:
      - db

  # https://github.com/docker-library/docs/blob/master/postgres/README.md
  db:
    image: app-db
    build:
      dockerfile: deploy/Dockerfile.postgres
      context: .
      # args:
      #   MIX_ENV: prod
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

# volumes:
#   db-data:
