# Build Elixir/Phoenix app

# App versions
ARG ELIXIR_VERSION=1.13.3
# ARG OTP_VERSION=23.3.4
ARG OTP_VERSION=24.2
ARG NODE_VERSION=16.14.1
# ARG NODE_VERSION=lts

ARG AWS_CLI_VERSION=2.0.61

# ARG ELIXIR_DEBIAN_VERSION=buster-20210208
ARG ELIXIR_DEBIAN_VERSION=bullseye-20210902-slim

# ARG DEBIAN_VERSION=buster-slim
ARG DEBIAN_VERSION=bullseye-slim

ARG BUILD_IMAGE_NAME=hexpm/elixir
ARG BUILD_IMAGE_TAG=${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${ELIXIR_DEBIAN_VERSION}

ARG INSTALL_IMAGE_NAME=debian
ARG INSTALL_IMAGE_TAG=bullseye-slim

# Deploy base image
ARG DEPLOY_IMAGE_NAME=debian
# ARG DEPLOY_IMAGE_TAG=buster-slim
ARG DEPLOY_IMAGE_TAG=bullseye-slim

# Docker registry for base images, default is docker.io
# If specified, should have a trailing slash
ARG REGISTRY=""

ARG PUBLIC_REGISTRY=""

# App name, used to name directories
ARG APP_NAME=app

# OS user that app runs under
# ARG APP_USER=app
ARG APP_USER=nonroot

# OS group that app runs under
ARG APP_GROUP="$APP_USER"

ARG APP_USER_ID=65532
ARG APP_GROUP_ID=$APP_USER_ID

# Dir that app runs under
ARG APP_DIR=/app

ARG HOME=$APP_DIR

# Set a specific LOCALE
ARG LANG=C.UTF-8

# Make apt-get be quiet
ARG DEBIAN_FRONTEND=noninteractive
ARG APT_OPTS="-y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends"
ARG APT_OPTS_UPDATE="-qq --no-install-recommends"

# Create build base image with OS dependencies
build-os-deps:
    FROM ${PUBLIC_REGISTRY}${BUILD_IMAGE_NAME}:${BUILD_IMAGE_TAG}

    # Configure apt caching for use with BuildKit
    # The default Debian image has special config to avoid caching, but we may want it.
    # RUN set -exu \
    #     && rm -f /etc/apt/apt.conf.d/docker-clean \
    #     && printf 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache \
    #     && printf 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99use-gzip-compression

    RUN set -exu && \
        apt-get update $APT_OPTS_UPDATE && \
        # Avoid warnings
        # apt-get -y install $APT_OPTS dialog apt-utils && \
        # Enable installation of packages over https
        apt-get -y install $APT_OPTS \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg \
            gnupg-agent \
            # software-properties-common \
            build-essential \
            git \
            lsb-release \
            && \

            # node needs python2
            # python-dev \
            # python-minimal \
            # python-pip \
            # python-setuptools && \

            # Installed via pip
            # python-virtualenv \

            # python3-dev \
            # python3-minimal \
            # python3-pip \
            # python3-setuptools \

        # Install node using n
        curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o /usr/local/bin/n && \
        chmod +x /usr/local/bin/n && \
        # Install lts version
        # && n lts \
        # Install specific version
        n "$NODE_VERSION" && \
        rm /usr/local/bin/n

        # Latest postgres
        # curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /etc/apt/trusted.gpg.d/postgresql-ACCC4CF8.asc && \
        # echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
        # echo "Package: *\nPin: release o=apt.postgresql.org\nPin-Priority: 500\n" | tee /etc/apt/preferences.d/pgdg.pref && \
        # apt-get update $APT_OPTS_UPDATE && \
        # apt-get -y install $APT_OPTS \
        #     libpq-dev \
        #     postgresql-client &&

        # Microsoft ODBC Driver for SQL Server
        # curl -sL https://packages.microsoft.com/keys/microsoft.asc -o /etc/apt/trusted.gpg.d/microsoft.asc && \
        # curl -s https://packages.microsoft.com/config/debian/11/prod.list -o /etc/apt/sources.list.d/mssql-release.list && \
        # export ACCEPT_EULA=Y && \
        # apt-get -qq update $APT_OPTS_UPDATE && apt-get -y install $APT_OPTS msodbcsql17 && \
        # rm -rf /var/lib/dpkg &&

        # apt-get clean &&
        # rm -rf /var/lib/apt/lists/*

    SAVE IMAGE --cache-hint

# Staging image for binaries which are copied into final deploy image
deploy-install:
    FROM ${REGISTRY}${INSTALL_IMAGE_NAME}:${INSTALL_IMAGE_TAG}

    # Configure apt caching for use with BuildKit
    # RUN set -exu && \
    #     rm -f /etc/apt/apt.conf.d/docker-clean && \
    #     echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache && \
    #     echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99use-gzip-compression

    RUN set -exu && \
        apt-get update $APT_OPTS_UPDATE && \
        # Avoid warnings
        # apt-get -y install $APT_OPTS dialog apt-utils \

        # Enable installation of packages over https
        apt-get -y install $APT_OPTS \
            # apt-transport-https \
            ca-certificates \
            curl \
            # gnupg-agent \
            # software-properties-common \
            # gnupg \
            unzip \
            locales \
            # Needed by beam
            libtinfo6 \
            && \
            locale-gen && \
            apt-get clean && \
            apt-get autoremove -y && \
            apt-get purge -y --auto-remove && \

            # info on installed packages
            # rm -rf /var/lib/dpkg && \
            # rm -rf /var/cache/debconf && \
            # Logs for installed packages
            rm -rf /var/log/apt/* && \
            rm -rf /var/log/dpkg.log && \
            # apt-get update files
            rm -rf /var/lib/apt/lists/*

    # If LANG=C.UTF-8 is not enough, build full featured locale
    # RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
    #
    # ENV LANG en_US.utf8

    # Install AWS CLI v2 from binary package
    # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
    # https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
    # RUN set -ex && \
    #     curl -sSfL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m)-${AWS_CLI_VERSION}.zip" -o "awscliv2.zip" && \
    #     unzip -q awscliv2.zip && \
    #     ./aws/install && \
    #     rm -rf ./aws && \
    #     rm awscliv2.zip

    SAVE ARTIFACT /usr/lib/locale/C.UTF-8

    SAVE IMAGE --cache-hint

deploy-base:
    FROM ${REGISTRY}${DEPLOY_IMAGE_NAME}:${DEPLOY_IMAGE_TAG}

    ENV LANG=$LANG
    ENV HOME=$APP_DIR

    COPY +deploy-install/C.UTF-8 /usr/lib/locale/C.UTF-8

    # Create OS user and group to run app under
    RUN groupadd -g $APP_GROUP_ID "$APP_GROUP" && \
        useradd -u $APP_USER_ID -g "$APP_GROUP" -d "$APP_DIR" "$APP_USER" && \
        rm /var/log/lastlog && \
        rm /var/log/faillog

    # Create dirs writable by app user
    RUN mkdir -p "/run/$APP_NAME" && \
        chown -R "${APP_USER}:${APP_GROUP}" \
            # Needed for RELEASE_TMP
            "/run/$APP_NAME"

    # Configure apt caching for use with BuildKit
    # RUN set -exu && \
    #     rm -f /etc/apt/apt.conf.d/docker-clean && \
    #     echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache && \
    #     echo 'Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/99use-gzip-compression

    # Create dirs needed by postgresql-client but stripped from slim
    # RUN seq 1 8 | xargs -I{} mkdir -p /usr/share/man/man{}

    RUN set -exu && \
        apt-get update $APT_OPTS_UPDATE && \

        apt-get install $APT_OPTS \
            ca-certificates \

            # Install openssl, allowing the app to listen on HTTPS.
            # May not be needed if handled outside the application (e.g. in load balancer).
            openssl \
            # tini \
            # bind-utils \

            # Needed by beam
            libtinfo6 \

            # Default Postgres
            # libpq-dev \
            # postgresql-client \

            # Latest PostgreSQL
            # curl && \
            # curl -sL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /etc/apt/trusted.gpg.d/postgresql-ACCC4CF8.asc && \
            # echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -sc)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
            # echo "Package: *\nPin: release o=apt.postgresql.org\nPin-Priority: 500\n" | tee /etc/apt/preferences.d/pgdg.pref && \
            # apt-get update $APT_OPTS_UPDATE && \
            # apt-get -y install $APT_OPTS \
            #     libpq-dev \
            #     postgresql-client \

            # Microsoft ODBC Driver for SQL Server
            # curl -sL https://packages.microsoft.com/keys/microsoft.asc -o /etc/apt/trusted.gpg.d/microsoft.asc && \
            # curl -s https://packages.microsoft.com/config/debian/10/prod.list -o /etc/apt/sources.list.d/mssql-release.list && \
            # export ACCEPT_EULA=Y && \
            # apt-get -qq update && apt-get -y install $APT_OPTS msodbcsql17 && \
            && \
        # apt-get remove curl \
        apt-get clean && \
        apt-get autoremove -y && \
        apt-get purge -y --auto-remove && \

        # info on installed packages
        # rm -rf /var/lib/dpkg && \
        # rm -rf /var/cache/debconf && \
        # Logs for installed packages
        rm -rf /var/log/apt/* && \
        rm -rf /var/log/dpkg.log && \
        # apt-get update files
        rm -rf /var/lib/apt/lists/*

    SAVE IMAGE --cache-hint

# Scan deploy image for security vulnerabilities
deploy-scan:
    FROM +deploy

    RUN apt-get -y install $APT_OPTS \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        gnupg-agent \
        # software-properties-common \
        lsb-release && \

        curl -sL https://aquasecurity.github.io/trivy-repo/deb/public.key -o /etc/apt/trusted.gpg.d/trivy.asc && \
        printf "deb https://aquasecurity.github.io/trivy-repo/deb %s main" "$(lsb_release -sc)" | tee -a /etc/apt/sources.list.d/trivy.list && \
        apt-get update $APT_OPTS_UPDATE && \
        apt-get -y install $APT_OPTS \
            trivy

    RUN \
        # Succeed for issues of severity = HIGH
        trivy filesystem --exit-code 0 --severity HIGH --no-progress / && \
        # Fail for issues of severity = CRITICAL
        trivy filesystem --exit-code 1 --severity CRITICAL --no-progress /
        # Fail for any issues
        # trivy filesystem -d --exit-code 1 --no-progress /

        # curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin && \
        # grype -vv --fail-on medium dir:/ \

    SAVE IMAGE --cache-hint
