---
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "<NAME>"
          ContainerPort: <PORT>
        PlatformVersion: "LATEST"
