---
# Build app in Docker and push to repo
#
# https://docs.aws.amazon.com/AmazonECS/latest/userguide/ecs-cd-pipeline.html
# Environment vars:
#   REGISTRY: ECS base registry
#   REPO_URL: ECS app repository
#   CACHE_REPO_URL: ECS repository for caching
#   CONTAINER_NAME: container name in service task definition
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-env-vars.html
#   AWS_DEFAULT_REGION
#   CODEBUILD_RESOLVED_SOURCE_VERSION
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2
env:
  variables:
    TEMPLATE_DIR: ecs
    # Enable docker buildx
    DOCKER_BUILDKIT: 1
    DOCKER_CLI_EXPERIMENTAL: enabled
    COMPOSE_DOCKER_CLI_BUILD: 1
phases:
  install:
    # runtime-versions:
    #   docker: 19
    commands:
      - /usr/sbin/service docker start
  pre_build:
    commands:
      - echo Build started on `date`
      - cat /etc/lsb-release
      - python3 --version
      - aws --version
      - docker version
      - docker-compose --version

      # Add support for cross arch builds (Arm)
      # - docker run --rm --privileged linuxkit/binfmt:v0.8
      # - cat /proc/sys/fs/binfmt_misc/qemu-aarch64
      # - ls -l /proc/sys/fs/binfmt_misc/*
      # - ls -1 /proc/sys/fs/binfmt_misc/qemu-*

      # Create builder instance
      - docker buildx create --name docker-container
      - docker buildx use docker-container
      - docker buildx inspect --bootstrap

      - echo Logging in to Amazon ECR...
      # Use amazon-ecr-credential-helper for login, installed in build image
      - mkdir -p /root/.docker
      - echo '{"credsStore":"ecr-login"}' | tee /root/.docker/config.json
      # Use old aws cli for login
      # - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      # Use new aws cli for login
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REGISTRY

      # - rm -rf /root/.cache/docker

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo "Starting build phase"
      # - REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/"
      - export REGISTRY="$(dirname $REPO_URL)/"
      # - BUILD_CACHE_REPO_URL="${REGISTRY}foo-app-ecs-build-cache"

      # - docker buildx use docker-container
      # - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build
      # - docker-compose run test mix test
      # - $TEMPLATE_DIR/build.sh

      # - docker buildx use default
      # - docker buildx bake -f docker-compose.yml --print
      # - docker buildx bake -f docker-compose.yml
      # - docker-compose run test mix test
      # - docker buildx use docker-container
      # - docker-compose push app

      # - docker buildx use docker-container

      - echo Building app container for tests...
      # - env DOCKERFILE=deploy/Dockerfile.debian MIX_ENV=test TARGET=test $TEMPLATE_DIR/build-test.sh
      - docker-compose build test

      # - echo Building db container...
      # - $TEMPLATE_DIR/build-db.sh

      - echo Running unit tests...
      - DATABASE_HOST=db docker-compose up test
      - DATABASE_HOST=db docker-compose run test mix test

      # Build final deploy container
      # - $TEMPLATE_DIR/build.sh
      # - env DOCKERFILE=deploy/Dockerfile.debian $TEMPLATE_DIR/build.sh
      - docker-compose build app
      - docker-compose push app

      # Build multiple architectures
      # - env PLATFORM="--platform linux/amd64,linux/arm64" DOCKERFILE=deploy/Dockerfile.alpine $TEMPLATE_DIR/build.sh

      # - echo Extracting assets from build container...
      # - $TEMPLATE_DIR/build-artifacts.sh

      # - CACHE_REPO_URL="${REGISTRY}foo-app-ecs-build-cache"
      # - CACHE_TYPE=registry $TEMPLATE_DIR/build.sh

      - echo "Writing image definition files..."
      # https://docs.aws.amazon.com/codepipeline/latest/userguide/file-reference.html
      # Generate imagedefinitions.json file for standard ECS deploy action
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$REPO_URL:$IMAGE_TAG" | tee imagedefinitions.json
      # Generate imageDetail.json file for CodeDeploy ECS blue/green deploy action
      - printf '{"ImageURI":"%s"}' "$REPO_URL:$IMAGE_TAG" | tee imageDetail.json

      - sed -i 's!<NAME>!'$CONTAINER_NAME'!g' $TEMPLATE_DIR/appspec.yml $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<PORT>!'$PORT'!g' ecs/appspec.yml $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<TASK_ROLE_ARN>!'$TASK_ROLE_ARN'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<EXECUTION_ROLE_ARN>!'$EXECUTION_ROLE_ARN'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<CPU>!'$CPU'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<MEMORY>!'$MEMORY'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<AWSLOGS_GROUP>!'$AWSLOGS_GROUP'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<AWSLOGS_REGION>!'$AWS_REGION'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<AWSLOGS_STREAM_PREFIX>!'$AWSLOGS_STREAM_PREFIX'!g' $TEMPLATE_DIR/taskdef.json

      - sed -i 's!<CONFIG_S3_BUCKET>!'$CONFIG_S3_BUCKET'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<CONFIG_S3_PREFIX>!'$CONFIG_S3_PREFIX'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<AWS_REGION>!'$AWS_REGION'!g' $TEMPLATE_DIR/taskdef.json
      - sed -i 's!<AWS_ACCOUNT_ID>!'$AWS_ACCOUNT_ID'!g' $TEMPLATE_DIR/taskdef.json

      - cat $TEMPLATE_DIR/appspec.yml
      - cat $TEMPLATE_DIR/taskdef.json
      - cp $TEMPLATE_DIR/appspec.yml .
      - cp $TEMPLATE_DIR/taskdef.json .

      - echo Build completed on `date`
  # post_build:
  #   commands:
artifacts:
  files:
    - imagedefinitions.json
    - imageDetail.json
    - appspec.yml
    - taskdef.json
cache:
  paths:
    - '/root/.cache/docker/**/*'
    # - '/var/lib/docker/**/*'
