---
name: CI Arm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::770916339360:role/foo-dev-codebuild-github-action-role
          aws-region: ap-northeast-1

      - name: Display Identity
        run: aws sts get-caller-identity

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: "foo-app-github-action-arm"
          buildspec-override: ecs/buildspec-earthly.yaml
          env-vars-for-codebuild: |
            custom,
            requester,
            event-name
        env:
          custom: my environment variable
          requester: ${{ github.actor }}
          event-name: ${{ github.event_name }}
