---
# Call CodeBuild as a runner to build Arm-CPU image
name: CI Arm
on: push
env:
  AWS_ROLE_TO_ASSUME: arn:aws:iam::770916339360:role/foo-dev-codebuild-github-action-role
  AWS_REGION: ap-northeast-1
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Needed to interact with GitHub's OIDC Token endpoint for AWS
      id-token: write
      contents: read
    steps:
      # - name: Dump event
      #   run: cat "$GITHUB_EVENT_PATH"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        # https://github.com/aws-actions/configure-aws-credentials
        # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # - name: Display AWS identity
      #   run: aws sts get-caller-identity

      # We don't need to check out source, just run codebuild
      # - name: Checkout
      #   uses: actions/checkout@v2

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1-node16
        with:
          project-name: "foo-app-github-action-arm"
          buildspec-override: ecs/buildspec-earthly.yml
          env-vars-for-codebuild: |
            custom,
            requester,
            event-name
        env:
          custom: my environment variable
          requester: ${{ github.actor }}
          event-name: ${{ github.event_name }}
