---
name: CI
on: push
# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#     types: [labeled,synchronize,reopened,unlabeled]
jobs:
  build:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000

    # Needed to interact with GitHub's OIDC Token endpoint for AWS
    permissions:
      id-token: write
      contents: read
    env:
      # REGISTRY: 770916339360.dkr.ecr.ap-northeast-1.amazonaws.com/
      # REGISTRY_NAME: 770916339360.dkr.ecr.ap-northeast-1.amazonaws.com
      IMAGE_NAME: foo-app
      AWS_ROLE: arn:aws:iam::770916339360:role/foo-dev-ecr-github-action-role
      AWS_REGION: ap-northeast-1
    steps:
      - name: Dump Event
        run: cat "$GITHUB_EVENT_PATH"

      # https://github.com/aws-actions/configure-aws-credentials
      # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Display AWS identity
        run: aws sts get-caller-identity

      # https://github.com/aws-actions/amazon-ecr-login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # - name: Login to ECR
      #   id: login-ecr
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY_NAME }}
      #     username: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # https://github.com/marketplace/actions/docker-login
      - name: Login to DockerHub
        id: login-docker-hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
          echo "::set-output name=run_id::${GITHUB_RUN_ID}"
          echo "::set-output name=run_num::${GITHUB_RUN_NUMBER}"

      # - name: Set up QEMU for multi-platform builds
      #   id: qemu
      #   uses: docker/setup-qemu-action@v2
      #   with:
      #     platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      # https://github.com/docker/build-push-action
      # - name: Build Docker test image
      #   id: docker-build-test
      #   uses: docker/build-push-action@v3
      #   env:
      #     REGISTRY: localhost:5000/
      #     PUBLIC_REGISTRY: "${{ steps.login-ecr.outputs.registry }}/"
      #   with:
      #     context: .
      #     builder: ${{ steps.buildx.outputs.name }}
      #     file: ./deploy/Dockerfile.debian
      #     # load: true
      #     push: true
      #     target: test-image
      #     # https://github.com/moby/buildkit#export-cache
      #     cache-from: type=gha,scope=${{ github.workflow }}-test
      #     cache-to: type=gha,scope=${{ github.workflow }}-test,mode=max
      #     tags: |
      #       localhost:5000/test/${{ env.IMAGE_NAME }}:test

      - name: Build test images
        env:
          REGISTRY: localhost:5000
        run: docker buildx bake -f docker-bake.gha.hcl --build-arg REGISTRY=${REGISTRY}

      - name: Run tests
        env:
          REGISTRY: localhost:5000/
          # PUBLIC_REGISTRY: "${{ steps.login-ecr.outputs.registry }}/"
        run: |
          docker-compose -f docker-compose.gha.yml up test
          docker-compose -f docker-compose.gha.yml run test mix test
          docker-compose -f docker-compose.gha.yml run test mix do credo, deps.audit, sobelow

      - name: Build Docker deploy image and push
        if: github.event_name != 'pull_request'
        id: docker-push
        uses: docker/build-push-action@v3
        env:
          REGISTRY: "${{ steps.login-ecr.outputs.registry }}/"
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./deploy/Dockerfile.debian
          push: true
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }},mode=max
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.run_id }}

          # push: ${{ github.event_name != 'pull_request' }}

      - name: Build Docker deploy image and push
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./deploy/Dockerfile.debian
          push: true
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,scope=${{ github.workflow }}
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
