on:
  schedule:
    - cron: '0 * * * *'

name: Security scan
env:
  # IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: foo-app
  IMAGE_OWNER: ${{ github.repository_owner }}
jobs:
  scan:
    name: Run security scans
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/foo-app:scan
      volumes:
        - /sarif-reports:/sarif-reports
    steps:
      - name: Check for dockerenv file
        run: trivy fs --no-progress /
